export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Works } from './Works'
export { default as ContactUs } from './ContactUs'
export { default as Services } from './Services'
export { default as AboutUs } from './AboutUs'
export { default as Clients } from './Clients'
export { default as Footer } from './Footer'